# Generated by Django 5.1.3 on 2025-11-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_project_internal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='general_notes',
            field=models.TextField(blank=True, help_text='ملاحظات عامة'),
        ),
        migrations.AddField(
            model_name='project',
            name='source_of_project',
            field=models.TextField(blank=True, help_text='مصدر المشروع'),
        ),
    ]
