# Generated by Django 5.1.3 on 2025-11-28 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_contract_general_notes_project_source_of_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='source_of_project',
        ),
        migrations.AddField(
            model_name='siteplan',
            name='source_of_project',
            field=models.TextField(blank=True, help_text='مصدر المشروع'),
        ),
    ]
