# Generated by Django 5.1.3 on 2025-11-29 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_add_contract_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildinglicense',
            name='contractor_name_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='buildinglicense',
            name='design_consultant_name_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='buildinglicense',
            name='supervision_consultant_name_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor_name_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
