# Generated by Django 5.1.3 on 2025-11-29 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_buildinglicense_contractor_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildinglicense',
            name='contractor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='buildinglicense',
            name='contractor_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
