# Generated by Django 5.1.3 on 2025-11-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_buildinglicense_contractor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='extensions',
            field=models.JSONField(blank=True, default=list, help_text="قائمة التمديدات: [{'reason': 'string', 'days': int, 'months': int}, ...]"),
        ),
        migrations.AddField(
            model_name='contract',
            name='owners',
            field=models.JSONField(blank=True, default=list, help_text="بيانات الملاك في العقد (قابلة للتحرير): [{'owner_name_ar': '...', 'owner_name_en': '...', 'phone': '...', 'email': '...', ...}, ...]"),
        ),
    ]
